'use client';

import { useEffect, useMemo, useState } from 'react';
import { FaEdit, FaFolderOpen, FaPlus, FaRedo, FaSave } from 'react-icons/fa';
import { ErpButton, ErpEmptyState, ErpInlineState, ErpSection, ErpSheet, ErpSkeleton, ErpStatus, ErpWorkspacePage } from '@/components/erp';
import { ErpCheckboxControl, ErpInput, ErpSelect } from '@/components/erp';
import { securityAPI } from '@/lib/api';

const inputClass = 'min-h-12 w-full rounded-xl border border-[var(--sds-border-subtle)] bg-[var(--sds-surface-panel)] px-3 text-sm outline-none focus:border-[var(--sds-accent)] focus:ring-2 focus:ring-[var(--sds-focus-ring)] dark:border-[var(--sds-border-default)] dark:bg-[var(--sds-surface-panel)]';
const labelClass = 'mb-2 block text-sm font-semibold sds-text-secondary ';
const emptyCategory = { id: '', name: '', description: '', displayOrder: 0, isActive: true, useReportTypes: true, useRelatedPersonnel: true };
const emptyType = { id: '', categoryId: '', name: '', description: '', displayOrder: 0, isActive: true, useRelatedPersonnel: true };
interface Category { id: string; name: string; description?: string | null; displayOrder: number; isActive: boolean; useReportTypes: boolean; useRelatedPersonnel: boolean; reportTypes?: any[] }

export default function ReportStructureSettingsPage() {
  const [categories, setCategories] = useState<Category[]>([]);
  const [types, setTypes] = useState<any[]>([]);
  const [categoryForm, setCategoryForm] = useState(emptyCategory);
  const [typeForm, setTypeForm] = useState(emptyType);
  const [categoryOpen, setCategoryOpen] = useState(false);
  const [typeOpen, setTypeOpen] = useState(false);
  const [showInactive, setShowInactive] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const load = async () => { setLoading(true); setError(''); try { const [categoryResponse, typeResponse] = await Promise.all([securityAPI.getInstantReportCategories(true), securityAPI.getInstantReportTypes(true)]); if (categoryResponse.data.success) setCategories(categoryResponse.data.data || []); if (typeResponse.data.success) setTypes(typeResponse.data.data || []); } catch (requestError: any) { setError(requestError.response?.data?.error || 'دریافت ساختار گزارش شیفت ناموفق بود.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visibleCategories = useMemo(() => categories.filter((category) => showInactive || category.isActive), [categories, showInactive]);

  const saveCategory = async () => { setSaving(true); setError(''); try { if (categoryForm.id) await securityAPI.updateInstantReportCategory(categoryForm.id, categoryForm); else await securityAPI.createInstantReportCategory(categoryForm); setMessage(categoryForm.id ? 'دسته‌بندی ویرایش شد.' : 'دسته‌بندی ثبت شد.'); setCategoryForm(emptyCategory); setCategoryOpen(false); await load(); } catch (requestError: any) { setError(requestError.response?.data?.error || 'ذخیره دسته‌بندی ناموفق بود.'); } finally { setSaving(false); } };
  const saveType = async () => { setSaving(true); setError(''); try { if (typeForm.id) await securityAPI.updateInstantReportType(typeForm.id, typeForm); else await securityAPI.createInstantReportType(typeForm); setMessage(typeForm.id ? 'نوع گزارش ویرایش شد.' : 'نوع گزارش ثبت شد.'); setTypeForm(emptyType); setTypeOpen(false); await load(); } catch (requestError: any) { setError(requestError.response?.data?.error || 'ذخیره نوع گزارش ناموفق بود.'); } finally { setSaving(false); } };
  const typesFor = (categoryId: string) => types.filter((type) => type.categoryId === categoryId && (showInactive || type.isActive));

  return <ErpWorkspacePage title="ساختار گزارش شیفت" backHref="/dashboard/security/settings" primaryAction={{ label: 'دسته‌بندی جدید', icon: FaPlus, variant: 'solid', onClick: () => { setCategoryForm(emptyCategory); setCategoryOpen(true); } }} secondaryActions={[{ label: 'به‌روزرسانی', icon: FaRedo, onClick: load }]}>
    {loading && !categories.length ? <ErpSkeleton lines={5} /> : error && !categories.length ? <ErpInlineState kind="error" title={error} action={{ label: 'تلاش مجدد', onClick: load }} /> : <>{message && <ErpInlineState kind="success" title={message} />}{error && <ErpInlineState kind="stale" title={error} action={{ label: 'تلاش مجدد', onClick: load }} />}<div className="flex justify-end"><label className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold"><ErpCheckboxControl checked={showInactive} onChange={(event) => setShowInactive(event.target.checked)} /> نمایش غیرفعال‌ها</label></div><ErpSection title="دسته‌بندی‌ها و نوع‌ها">{!visibleCategories.length ? <ErpEmptyState icon={FaFolderOpen} title="دسته‌بندی فعالی تعریف نشده است" /> : <div className="divide-y divide-[var(--sds-border-subtle)] dark:divide-[var(--sds-border-subtle)]">{visibleCategories.map((category) => <section key={category.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-bold sds-text-primary ">{category.name}</h2><ErpStatus label={category.isActive ? 'فعال' : 'غیرفعال'} tone={category.isActive ? 'success' : 'neutral'} /></div><p className="mt-1 text-xs sds-text-muted">ترتیب {category.displayOrder.toLocaleString('fa-IR')} · {category.useReportTypes ? 'دارای نوع گزارش' : 'بدون نوع گزارش'}</p></div><div className="flex gap-2"><ErpButton label="نوع جدید" icon={FaPlus} onClick={() => { setTypeForm({ ...emptyType, categoryId: category.id }); setTypeOpen(true); }} variant="ghost" /><ErpButton label="ویرایش" icon={FaEdit} onClick={() => { setCategoryForm({ id: category.id, name: category.name, description: category.description || '', displayOrder: category.displayOrder || 0, isActive: category.isActive, useReportTypes: category.useReportTypes, useRelatedPersonnel: category.useRelatedPersonnel }); setCategoryOpen(true); }} variant="ghost" /></div></div>{category.useReportTypes && <div className="mt-3 divide-y divide-[var(--sds-border-subtle)] rounded-xl bg-[var(--sds-surface-subtle)] px-3 dark:divide-[var(--sds-border-subtle)] dark:bg-[var(--sds-surface-subtle)]">{typesFor(category.id).map((type) => <div key={type.id} className="flex min-h-13 items-center gap-3 py-2"><span className="min-w-0 flex-1 truncate text-sm font-semibold">{type.name}</span><ErpStatus label={type.isActive ? 'فعال' : 'غیرفعال'} tone={type.isActive ? 'success' : 'neutral'} /><ErpButton label="ویرایش" icon={FaEdit} onClick={() => { setTypeForm({ id: type.id, categoryId: type.categoryId, name: type.name, description: type.description || '', displayOrder: type.displayOrder || 0, isActive: type.isActive, useRelatedPersonnel: type.useRelatedPersonnel }); setTypeOpen(true); }} variant="ghost" /></div>)}{!typesFor(category.id).length && <p className="py-3 text-xs sds-text-muted">نوع فعالی تعریف نشده است.</p>}</div>}</section>)}</div>}</ErpSection></>}
    <ErpSheet open={categoryOpen} onClose={() => setCategoryOpen(false)} title={categoryForm.id ? 'ویرایش دسته‌بندی' : 'دسته‌بندی جدید'}><div className="space-y-4"><label className="block"><span className={labelClass}>نام</span><ErpInput className={inputClass} value={categoryForm.name} onChange={(event) => setCategoryForm({ ...categoryForm, name: event.target.value })} /></label><label className="block"><span className={labelClass}>ترتیب نمایش</span><ErpInput type="number" className={inputClass} value={categoryForm.displayOrder} onChange={(event) => setCategoryForm({ ...categoryForm, displayOrder: Number(event.target.value) })} /></label><label className="flex min-h-11 items-center gap-2"><ErpCheckboxControl checked={categoryForm.useReportTypes} onChange={(event) => setCategoryForm({ ...categoryForm, useReportTypes: event.target.checked })} /> استفاده از نوع گزارش</label><label className="flex min-h-11 items-center gap-2"><ErpCheckboxControl checked={categoryForm.useRelatedPersonnel} onChange={(event) => setCategoryForm({ ...categoryForm, useRelatedPersonnel: event.target.checked })} /> امکان انتخاب افراد مرتبط</label><label className="flex min-h-11 items-center gap-2"><ErpCheckboxControl checked={categoryForm.isActive} onChange={(event) => setCategoryForm({ ...categoryForm, isActive: event.target.checked })} /> فعال</label><div className="flex justify-end"><ErpButton label={saving ? 'در حال ذخیره…' : 'ذخیره'} icon={FaSave} onClick={saveCategory} disabled={saving || !categoryForm.name.trim()} variant="solid" /></div></div></ErpSheet>
    <ErpSheet open={typeOpen} onClose={() => setTypeOpen(false)} title={typeForm.id ? 'ویرایش نوع گزارش' : 'نوع گزارش جدید'}><div className="space-y-4"><label className="block"><span className={labelClass}>دسته‌بندی</span><ErpSelect className={inputClass} value={typeForm.categoryId} onChange={(event) => setTypeForm({ ...typeForm, categoryId: event.target.value })}><option value="">انتخاب دسته‌بندی</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</ErpSelect></label><label className="block"><span className={labelClass}>نام</span><ErpInput className={inputClass} value={typeForm.name} onChange={(event) => setTypeForm({ ...typeForm, name: event.target.value })} /></label><label className="block"><span className={labelClass}>ترتیب نمایش</span><ErpInput type="number" className={inputClass} value={typeForm.displayOrder} onChange={(event) => setTypeForm({ ...typeForm, displayOrder: Number(event.target.value) })} /></label><label className="flex min-h-11 items-center gap-2"><ErpCheckboxControl checked={typeForm.useRelatedPersonnel} onChange={(event) => setTypeForm({ ...typeForm, useRelatedPersonnel: event.target.checked })} /> امکان انتخاب افراد مرتبط</label><label className="flex min-h-11 items-center gap-2"><ErpCheckboxControl checked={typeForm.isActive} onChange={(event) => setTypeForm({ ...typeForm, isActive: event.target.checked })} /> فعال</label><div className="flex justify-end"><ErpButton label={saving ? 'در حال ذخیره…' : 'ذخیره'} icon={FaSave} onClick={saveType} disabled={saving || !typeForm.categoryId || !typeForm.name.trim()} variant="solid" /></div></div></ErpSheet>
  </ErpWorkspacePage>;
}
