'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { FaChartLine, FaClock, FaExclamationTriangle, FaFileExcel, FaFilePdf, FaHistory, FaRedo, FaShieldAlt, FaUsers } from 'react-icons/fa';
import { departmentsAPI, securityAPI } from '@/lib/api';
import PersianCalendar from '@/lib/persian-calendar';
import PersianCalendarComponent from '@/components/PersianCalendar';
import { ErpButton, ErpCard, ErpEmptyState, ErpLoading, ErpPage, ErpSection, ErpSegmentedControl } from '@/components/erp';

const inputClass = 'min-h-12 w-full rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-[#074747] focus:bg-white dark:border-slate-700 dark:bg-slate-800 dark:text-white';
type Scope = 'attendance' | 'performance';

export default function ReportsPage() {
  const [scope, setScope] = useState<Scope>('attendance'); const [data, setData] = useState<any>(null); const [performance, setPerformance] = useState<any>(null);
  const [departments, setDepartments] = useState<any[]>([]); const [shifts, setShifts] = useState<any[]>([]); const [personnel, setPersonnel] = useState<any[]>([]);
  const [range, setRange] = useState({ startDate: PersianCalendar.now(), endDate: PersianCalendar.now() }); const [departmentId, setDepartmentId] = useState(''); const [shiftId, setShiftId] = useState(''); const [personnelId, setPersonnelId] = useState(''); const [sessionStatus, setSessionStatus] = useState(''); const [coverageStatus, setCoverageStatus] = useState(''); const [activityType, setActivityType] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [exporting, setExporting] = useState<'pdf' | 'excel' | null>(null);
  const params = () => ({ startDate: PersianCalendar.toGregorian(range.startDate).toISOString(), endDate: PersianCalendar.toGregorian(range.endDate).toISOString(), departmentId: departmentId || undefined, shiftId: shiftId || undefined });
  const load = async () => { try { setLoading(true); setError(''); if (scope === 'attendance') setData((await securityAPI.getSecurityReportSummary(params())).data.data); else setPerformance((await securityAPI.getSecurityPersonnelPerformance({ ...params(), personnelId: personnelId || undefined, sessionStatus: sessionStatus || undefined, coverageStatus: coverageStatus || undefined, activityType: activityType || undefined })).data.data); } catch (err: any) { setError(err.response?.data?.error || 'دریافت گزارش ناموفق بود.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [scope, range, departmentId, shiftId, personnelId, sessionStatus, coverageStatus, activityType]);
  useEffect(() => { Promise.all([departmentsAPI.getDepartments(), securityAPI.getShifts(), securityAPI.getPersonnel()]).then(([d, s, p]) => { setDepartments(d.data.data || []); setShifts(s.data.data || []); setPersonnel(p.data.data || []); }).catch(() => undefined); }, []);
  const preset = (days: number) => { const end = new Date(); setRange({ startDate: PersianCalendar.toPersian(new Date(end.getTime() - (days - 1) * 86400000)), endDate: PersianCalendar.toPersian(end) }); };
  const exportReport = async (format: 'pdf' | 'excel') => { try { setExporting(format); const result = await securityAPI.exportSecurityReport(format, params()); const url = URL.createObjectURL(new Blob([result.data])); const a = document.createElement('a'); a.href = url; a.download = `security-report.${format === 'pdf' ? 'pdf' : 'xlsx'}`; a.click(); URL.revokeObjectURL(url); } catch (err: any) { setError(err.response?.data?.error || 'ساخت خروجی ناموفق بود.'); } finally { setExporting(null); } };
  if (loading) return <ErpLoading />;
  if (error) return <ErpPage eyebrow="حراست" title="گزارش‌های حراست"><ErpEmptyState title="گزارش در دسترس نیست" description={error} icon={FaExclamationTriangle} action={{ label: 'تلاش مجدد', icon: FaRedo, onClick: load }} /></ErpPage>;
  const attendance = data?.attendance || {}; const trend = data?.attendanceTrend || []; const summaries = performance?.summaries || [];
  const metrics = scope === 'attendance' ? [{ label: 'نرخ حضور', value: `${attendance.attendanceRate || 0}%`, icon: FaUsers, tone: 'success' as const }, { label: 'غیبت', value: attendance.absent || 0, icon: FaExclamationTriangle, tone: 'danger' as const }, { label: 'شیفت تکمیل‌شده', value: data?.shifts?.completedShifts || 0, icon: FaClock, tone: 'info' as const }, { label: 'درخواست در انتظار', value: data?.exceptions?.pending || 0, icon: FaChartLine, tone: 'warning' as const }] : [{ label: 'نیروها', value: summaries.length, icon: FaUsers, tone: 'info' as const }, { label: 'تکمیل‌شده', value: summaries.reduce((n: number, item: any) => n + item.completed, 0), icon: FaClock, tone: 'success' as const }, { label: 'عدم حضور', value: summaries.reduce((n: number, item: any) => n + item.noShows, 0), icon: FaExclamationTriangle, tone: 'danger' as const }, { label: 'گزارش‌ها', value: summaries.reduce((n: number, item: any) => n + item.logEntries, 0), icon: FaShieldAlt, tone: 'warning' as const }];
  return <ErpPage eyebrow="حراست" title="گزارش‌های حراست" description="حضور کارکنان و عملکرد عملیاتی نیروهای حراست" metrics={metrics} actions={[{ label: 'به‌روزرسانی', icon: FaRedo, tone: 'neutral', onClick: load }, ...(scope === 'attendance' ? [{ label: exporting === 'pdf' ? 'در حال ساخت…' : 'PDF', icon: FaFilePdf, onClick: () => exportReport('pdf'), disabled: !!exporting }, { label: exporting === 'excel' ? 'در حال ساخت…' : 'Excel', icon: FaFileExcel, tone: 'success' as const, onClick: () => exportReport('excel'), disabled: !!exporting }] : [])]}>
    <ErpSegmentedControl value={scope} onChange={setScope} options={[{ value: 'attendance', label: 'حضور و غیاب کارکنان', icon: FaUsers }, { value: 'performance', label: 'عملکرد نیروهای حراست', icon: FaShieldAlt }]} />
    <ErpSection title="فیلتر گزارش" description="فیلترها و بازه زمانی در گزارش و تاریخچه شیفت‌ها حفظ می‌شوند."><div className="mb-3 flex flex-wrap gap-2"><ErpButton label="امروز" variant="soft" onClick={() => preset(1)} /><ErpButton label="۷ روز اخیر" variant="soft" onClick={() => preset(7)} /><ErpButton label="۳۰ روز اخیر" variant="soft" onClick={() => preset(30)} /></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-5"><label><span className="mb-2 block text-sm font-medium">از تاریخ</span><PersianCalendarComponent value={range.startDate} onChange={(startDate) => setRange((old) => ({ ...old, startDate }))} /></label><label><span className="mb-2 block text-sm font-medium">تا تاریخ</span><PersianCalendarComponent value={range.endDate} onChange={(endDate) => setRange((old) => ({ ...old, endDate }))} /></label>{scope === 'attendance' ? <><label><span className="mb-2 block text-sm font-medium">بخش</span><select className={inputClass} value={departmentId} onChange={(e) => setDepartmentId(e.target.value)}><option value="">همه بخش‌ها</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.namePersian}</option>)}</select></label><label><span className="mb-2 block text-sm font-medium">شیفت</span><select className={inputClass} value={shiftId} onChange={(e) => setShiftId(e.target.value)}><option value="">همه شیفت‌ها</option>{shifts.map((x) => <option key={x.id} value={x.id}>{x.namePersian}</option>)}</select></label></> : <><label><span className="mb-2 block text-sm font-medium">نیروی حراست</span><select className={inputClass} value={personnelId} onChange={(e) => setPersonnelId(e.target.value)}><option value="">همه نیروها</option>{personnel.map((x) => <option key={x.id} value={x.id}>{x.user.firstName} {x.user.lastName}</option>)}</select></label><label><span className="mb-2 block text-sm font-medium">وضعیت شیفت</span><select className={inputClass} value={sessionStatus} onChange={(e) => setSessionStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="CLOSED">تکمیل‌شده</option><option value="FORCE_CLOSED">بسته‌شده مدیر</option><option value="ACTIVE">فعال</option></select></label><label><span className="mb-2 block text-sm font-medium">پوشش</span><select className={inputClass} value={coverageStatus} onChange={(e) => setCoverageStatus(e.target.value)}><option value="">همه</option><option value="COVERED">کامل</option><option value="NEEDS_REPLACEMENT">جایگزین</option><option value="EMERGENCY_UNCOVERED">اضطراری</option></select></label></>}</div></ErpSection>
    {scope === 'attendance' ? <ErpSection title="روند روزانه"><ErpCard className="overflow-x-auto p-0"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-slate-50"><tr>{['تاریخ','کل','حاضر','غایب','تأخیر','ماموریت','مرخصی'].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{trend.map((x: any) => <tr key={x.date} className="border-t"><td className="px-4 py-3">{new Date(x.date).toLocaleDateString('fa-IR')}</td><td className="px-4 py-3">{x.total}</td><td className="px-4 py-3 text-emerald-600">{x.present}</td><td className="px-4 py-3 text-red-600">{x.absent}</td><td className="px-4 py-3 text-amber-600">{x.late}</td><td className="px-4 py-3">{x.mission}</td><td className="px-4 py-3">{x.leave}</td></tr>)}</tbody></table></ErpCard></ErpSection> : <ErpSection title="خلاصه عملکرد نیروها" description="با دکمه تاریخچه، جزئیات کامل شیفت‌های همان نیرو را ببینید."><ErpCard className="overflow-x-auto p-0"><table className="w-full min-w-[980px] text-right text-sm"><thead className="bg-slate-50"><tr>{['نیرو','شیفت','برنامه','حضور','تأخیر','عدم حضور','تکمیل','گشت','گزارش',''].map((h, i) => <th key={`${h}-${i}`} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{summaries.map((x: any) => <tr key={x.id} className="border-t"><td className="px-4 py-3 font-semibold">{x.name}</td><td className="px-4 py-3">{x.shift}</td><td className="px-4 py-3">{x.plannedSlots}</td><td className="px-4 py-3">{x.attended}</td><td className="px-4 py-3 text-amber-600">{x.late}</td><td className="px-4 py-3 text-red-600">{x.noShows}</td><td className="px-4 py-3 text-emerald-600">{x.completed}</td><td className="px-4 py-3">{x.patrols}</td><td className="px-4 py-3">{x.logEntries}</td><td className="px-4 py-3"><Link href={`/dashboard/security/reports/${x.id}?startDate=${encodeURIComponent(range.startDate)}&endDate=${encodeURIComponent(range.endDate)}`} className="inline-flex items-center gap-2 rounded-lg border border-[#074747]/30 px-3 py-2 text-xs font-semibold text-[#074747]"><FaHistory />تاریخچه شیفت‌ها</Link></td></tr>)}</tbody></table></ErpCard></ErpSection>}
  </ErpPage>;
}
