const labels: Record<string, string> = {
  HR_PROCESSOR: "کارشناس منابع انسانی",
  HR_MANAGER: "مدیر منابع انسانی",
  HR_PAYROLL_PROCESSOR: "کارشناس حقوق و دستمزد",
  HR_PAYROLL_MANAGER: "مدیر حقوق و دستمزد",
  FINANCE_RECORDER: "کارشناس امور مالی",
  FINANCE_MANAGER: "مدیر امور مالی",
  HIRING_MANAGER: "مدیر استخدام‌کننده",
  COMPANY_MANAGER: "مدیریت شرکت",
  CANDIDATE: "متقاضی",
  PERSONNEL: "پرسنل",
  APPROVED: "تأییدشده",
  REJECTED: "ردشده",
  NOT_STARTED: "شروع‌نشده",
  IN_PROGRESS: "در حال انجام",
  COMPLETE: "تکمیل‌شده",
  COMPLETED: "تکمیل‌شده",
  ACTIVE: "فعال",
  VOIDED: "باطل‌شده",
  SUPERSEDED: "جایگزین‌شده",
  EXEMPT: "معاف",
  PENDING: "در انتظار",
  POSITIVE: "مثبت",
  NEGATIVE: "منفی",
  CANCELLED: "لغوشده",
  WAIVED: "معاف‌شده با دلیل",
  INITIAL_REJECTED: "رد اولیه",
  RESERVE: "رد/ذخیره",
  REPEAT_REQUIRED: "نیازمند تکرار",
  DELIVERED: "تحویل‌شده",
  UNKNOWN: "خطای طبقه‌بندی",
  SENT: "ارسال‌شده",
  FAILED: "ناموفق",
  ACCEPTED: "پذیرفته‌شده",
  DECLINED: "ردشده",
  PHONE: "تماس تلفنی",
  IN_PERSON: "جلسه حضوری",
  VIDEO_CALL: "تماس تصویری",
  HR_PROCESSOR_OFFLINE: "ثبت آفلاین توسط کارشناس منابع انسانی",
  APPLICANT_PORTAL: "درگاه متقاضی",
  NATIONAL_CARD: "کارت ملی",
  BIRTH_CERTIFICATE: "شناسنامه",
  EDUCATION_CERTIFICATE: "مدرک تحصیلی",
  MILITARY_CARD: "کارت وضعیت نظام وظیفه",
  OTHER: "سایر",
  ORIGINAL: "اصل",
  COPY: "رونوشت",
  SCAN: "نسخه اسکن‌شده",
  CHEQUE: "چک",
  PROMISSORY_NOTE: "سفته",
  GUARANTEE: "ضمانت‌نامه",
  CASH: "وجه نقد",
  RETURNED: "بازگردانده‌شده",
  HIRED: "استخدام‌شده",
  RECEIVED: "دریافت‌شده",
  VERIFIED: "تأییدشده",
  MISSING: "دریافت‌نشده",
  MISMATCH: "مغایرت",
  UNREADABLE: "خوانا نیست",
  UNDERTAKING: "تعهدنامه",
  BIRTH_CERTIFICATE_ALL_PAGES: "تمام صفحات شناسنامه",
  BIRTH_CERTIFICATE_EXPLANATIONS: "صفحه توضیحات شناسنامه",
  NATIONAL_ID_FRONT: "روی کارت ملی",
  NATIONAL_ID_BACK: "پشت کارت ملی",
  MILITARY: "مدرک وضعیت نظام وظیفه",
  EDUCATION: "مدرک تحصیلی",
  PHOTO: "عکس پرسنلی",
  MISSION: "مأموریت",
  HOURLY_LEAVE: "مرخصی ساعتی",
  SICK_LEAVE: "مرخصی استعلاجی",
  VACATION: "مرخصی",
  ABSENCE: "غیبت",
  EMERGENCY_LEAVE: "مرخصی اضطراری",
  PERSONAL_LEAVE: "مرخصی شخصی",
};

export const authorityLabel = (value?: string | null) =>
  (value && labels[value]) || (value ? "خطای طبقه‌بندی" : "—");

export const hrDisplayLabel = authorityLabel;

export const assessmentTypeLabel = (value?: string | null) => {
  const assessmentLabels: Record<string, string> = {
    DISC: "DISC (ارزیابی الگوی رفتاری دیسک)",
    BIG_FIVE: "BIG FIVE (ارزیابی پنج عامل بزرگ شخصیت)",
    EQ: "EQ (ارزیابی هوش هیجانی)",
    OTHER: "سایر",
  };
  return (value && assessmentLabels[value]) || authorityLabel(value);
};
