ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'PERSONNEL_CURRENT';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'PERSONNEL_INACTIVE_ENDED';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'USER_PERSONNEL_LINKED';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'USER_ACCESS_ONLY';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'USER_LINKAGE_UNRESOLVED';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'EMPLOYMENT_CURRENT';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'EMPLOYMENT_ENDED';
ALTER TYPE "HrReconciliationPrimaryState" ADD VALUE IF NOT EXISTS 'NEUTRAL_HISTORY';

ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'ACCESS_ONLY_USER';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'DIFFERENT_PEOPLE';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'SHARED_IDENTITY';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'STILL_AMBIGUOUS';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'ORGANIZATION_MAPPED';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'ORGANIZATION_CREATED';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'ORGANIZATION_HISTORICAL';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'START_DATE_UNRECOVERABLE';
ALTER TYPE "HrReconciliationReviewOutcome" ADD VALUE IF NOT EXISTS 'LEGACY_ONLY_CONFIRMED';
