'use client';
import { ErpButton, ErpInput, ErpPressable, ErpSegmentedControl, ErpSelect, ErpTextarea } from '@/components/erp';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  FaArrowRight,
  FaSave,
  FaEye,
  FaFileContract,
  FaPlus,
  FaTrash,
  FaCode,
  FaTable,
  FaCalculator
} from 'react-icons/fa';
import { contractTemplatesAPI } from '@/lib/api';
import { SalesAuthoringPage, SalesAuthoringSection } from '@/features/sales/authoring/SalesAuthoringUi';

interface TemplateVariable {
  key: string;
  type: 'text' | 'number' | 'date' | 'array';
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  calculated?: boolean;
  fields?: Record<string, TemplateVariable>;
}

interface TemplateStructure {
  sections: string[];
  tableConfig: {
    maxRows: number;
    columns: Array<{
      key: string;
      label: string;
      type: string;
      required?: boolean;
      autoIncrement?: boolean;
      calculated?: boolean;
    }>;
  };
}

interface TemplateCalculations {
  formulas: Record<string, string>;
  persianNumberConversion: boolean;
}

export default function CreateContractTemplatePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [activeTab, setActiveTab] = useState<'basic' | 'content' | 'variables' | 'structure' | 'calculations'>('basic');

  const [formData, setFormData] = useState({
    name: '',
    namePersian: '',
    description: '',
    category: 'sales',
    content: '',
    variables: {} as Record<string, TemplateVariable>,
    structure: {} as TemplateStructure,
    calculations: {} as TemplateCalculations
  });

  const [newVariable, setNewVariable] = useState({
    key: '',
    type: 'text' as const,
    label: '',
    required: false,
    autoGenerated: false,
    calculated: false
  });

  const categories = [
    { value: 'sales', label: 'فروش' },
    { value: 'service', label: 'خدمات' },
    { value: 'maintenance', label: 'نگهداری' },
    { value: 'general', label: 'عمومی' }
  ];

  const variableTypes = [
    { value: 'text', label: 'متن' },
    { value: 'number', label: 'عدد' },
    { value: 'date', label: 'تاریخ' },
    { value: 'array', label: 'آرایه' }
  ];

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    if (!formData.name.trim()) {
      newErrors.name = 'نام قالب الزامی است';
    }
    if (!formData.namePersian.trim()) {
      newErrors.namePersian = 'نام فارسی قالب الزامی است';
    }
    if (!formData.content.trim()) {
      newErrors.content = 'محتوای قالب الزامی است';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) {
      return;
    }

    setLoading(true);
    try {
      const response = await contractTemplatesAPI.create({
        name: formData.name,
        namePersian: formData.namePersian,
        description: formData.description || undefined,
        category: formData.category,
        content: formData.content,
        variables: Object.keys(formData.variables).length > 0 ? formData.variables : undefined,
        structure: Object.keys(formData.structure).length > 0 ? formData.structure : undefined,
        calculations: Object.keys(formData.calculations).length > 0 ? formData.calculations : undefined
      });

      if (response.data.success) {
        router.push('/dashboard/contract-templates');
      } else {
        setErrors({ general: response.data.error || 'خطا در ایجاد قالب' });
      }
    } catch (error: any) {
      console.error('Create template error:', error);
      setErrors({ general: error.response?.data?.error || 'خطا در ارتباط با سرور' });
    } finally {
      setLoading(false);
    }
  };

  const addVariable = () => {
    if (!newVariable.key || !newVariable.label) {
      setErrors({ variable: 'کلید و برچسب متغیر الزامی است' });
      return;
    }

    if (formData.variables[newVariable.key]) {
      setErrors({ variable: 'متغیر با این کلید قبلا وجود دارد' });
      return;
    }

    setFormData({
      ...formData,
      variables: {
        ...formData.variables,
        [newVariable.key]: { ...newVariable }
      }
    });

    setNewVariable({
      key: '',
      type: 'text',
      label: '',
      required: false,
      autoGenerated: false,
      calculated: false
    });
    setErrors({});
  };

  const removeVariable = (key: string) => {
    const newVariables = { ...formData.variables };
    delete newVariables[key];
    setFormData({ ...formData, variables: newVariables });
  };

  const updateStructure = (field: keyof TemplateStructure, value: any) => {
    setFormData({
      ...formData,
      structure: {
        ...formData.structure,
        [field]: value
      }
    });
  };

  const updateCalculations = (field: keyof TemplateCalculations, value: any) => {
    setFormData({
      ...formData,
      calculations: {
        ...formData.calculations,
        [field]: value
      }
    });
  };

  const tabs = [
    { id: 'basic', label: 'اطلاعات پایه', icon: FaFileContract },
    { id: 'content', label: 'محتوای قالب', icon: FaCode },
    { id: 'variables', label: 'متغیرها', icon: FaTable },
    { id: 'structure', label: 'ساختار', icon: FaTable },
    { id: 'calculations', label: 'محاسبات', icon: FaCalculator }
  ];

  return (
    <SalesAuthoringPage
      title="ایجاد قالب قرارداد جدید"
      description="قالب جدید برای قراردادهای فروش"
      backHref="/dashboard/contract-templates"
      feedback={errors.general
        ? { kind: 'error', title: errors.general }
        : (formData.name || formData.namePersian || formData.description || formData.content || Object.keys(formData.variables).length > 0 || Object.keys(formData.structure).length > 0 || Object.keys(formData.calculations).length > 0)
          ? { kind: 'stale', title: 'تغییرات قالب تا ثبت نهایی ذخیره نمی‌شوند.' }
          : undefined}
      progress={{ current: tabs.findIndex((tab) => tab.id === activeTab) + 1, total: tabs.length, label: tabs.find((tab) => tab.id === activeTab)?.label || '' }}
    >

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Tab Navigation */}
        <ErpSegmentedControl
          value={activeTab}
          onChange={setActiveTab}
          options={tabs.map((tab) => ({ value: tab.id as typeof activeTab, label: tab.label, icon: tab.icon }))}
        />

        {/* Basic Information Tab */}
        {activeTab === 'basic' && (
          <SalesAuthoringSection title="اطلاعات پایه" className="space-y-6">

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="template-name" className="block text-[var(--sds-text-primary)] font-medium mb-2">نام قالب (انگلیسی)</label>
                <ErpInput
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full"
                  placeholder="Sales Contract Template"
                  id="template-name"
                  aria-invalid={Boolean(errors.name)}
                  aria-describedby={errors.name ? 'template-name-error' : undefined}
                />
                {errors.name && <p id="template-name-error" role="alert" className="text-[var(--sds-danger)] text-sm mt-1">{errors.name}</p>}
              </div>

              <div>
                <label htmlFor="template-namePersian" className="block text-[var(--sds-text-primary)] font-medium mb-2">نام قالب (فارسی)</label>
                <ErpInput
                  type="text"
                  value={formData.namePersian}
                  onChange={(e) => setFormData({ ...formData, namePersian: e.target.value })}
                  className="w-full"
                  placeholder="قالب قرارداد فروش"
                  id="template-namePersian"
                  aria-invalid={Boolean(errors.namePersian)}
                  aria-describedby={errors.namePersian ? 'template-namePersian-error' : undefined}
                />
                {errors.namePersian && <p id="template-namePersian-error" role="alert" className="text-[var(--sds-danger)] text-sm mt-1">{errors.namePersian}</p>}
              </div>

              <div>
                <label className="block text-[var(--sds-text-primary)] font-medium mb-2">دسته‌بندی</label>
                <ErpSelect
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full"
                >
                  {categories.map(cat => (
                    <option key={cat.value} value={cat.value}>{cat.label}</option>
                  ))}
                </ErpSelect>
              </div>

              <div className="md:col-span-2">
                <label className="block text-[var(--sds-text-primary)] font-medium mb-2">توضیحات</label>
                <ErpTextarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full h-24"
                  placeholder="توضیحات کوتاه درباره قالب..."
                />
              </div>
            </div>
          </SalesAuthoringSection>
        )}

        {/* Content Tab */}
        {activeTab === 'content' && (
          <SalesAuthoringSection title="محتوای قالب" className="space-y-6">

            <div>
              <label htmlFor="template-content" className="block text-[var(--sds-text-primary)] font-medium mb-2">محتوای HTML قالب</label>
              <ErpTextarea
                value={formData.content}
                onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                className="w-full h-96 font-mono text-sm"
                placeholder="محتوای HTML قالب با متغیرهای {{variableName}}..."
                id="template-content"
                aria-invalid={Boolean(errors.content)}
                aria-describedby={errors.content ? 'template-content-error' : undefined}
              />
              {errors.content && <p id="template-content-error" role="alert" className="text-[var(--sds-danger)] text-sm mt-1">{errors.content}</p>}
            </div>

            <div className="bg-[var(--sds-surface-raised)] p-4 rounded-lg">
              <h3 className="text-[var(--sds-text-primary)] font-medium mb-2">راهنمای متغیرها:</h3>
              <ul className="text-[var(--sds-text-muted)] text-sm space-y-1">
                <li>• از {'{{variableName}}'} برای متغیرها استفاده کنید</li>
                <li>• از {'{{tableRows}}'} برای ردیف‌های جدول استفاده کنید</li>
                <li>• از CSS inline برای استایل‌دهی استفاده کنید</li>
                <li>• جهت RTL و فونت فارسی را در نظر بگیرید</li>
              </ul>
            </div>
          </SalesAuthoringSection>
        )}

        {/* Variables Tab */}
        {activeTab === 'variables' && (
          <SalesAuthoringSection title="متغیرهای قالب" className="space-y-6">

            {/* Add New Variable */}
            <SalesAuthoringSection title="افزودن متغیر جدید">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">کلید متغیر</label>
                  <ErpInput
                    type="text"
                    value={newVariable.key}
                    onChange={(e) => setNewVariable({ ...newVariable, key: e.target.value })}
                    className="w-full"
                    placeholder="buyerName"
                  />
                </div>
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">برچسب</label>
                  <ErpInput
                    type="text"
                    value={newVariable.label}
                    onChange={(e) => setNewVariable({ ...newVariable, label: e.target.value })}
                    className="w-full"
                    placeholder="نام خریدار"
                  />
                </div>
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">نوع</label>
                  <ErpSelect
                    value={newVariable.type}
                    onChange={(e) => setNewVariable({ ...newVariable, type: e.target.value as any })}
                    className="w-full"
                  >
                    {variableTypes.map(type => (
                      <option key={type.value} value={type.value}>{type.label}</option>
                    ))}
                  </ErpSelect>
                </div>
                <div className="flex items-end">
                  <ErpPressable
                    type="button"
                    onClick={addVariable}
                    tone="primary"
                    variant="solid"
                    className="px-4 py-2 w-full flex items-center justify-center gap-2"
                  >
                    <FaPlus className="h-4 w-4" />
                    <span>افزودن</span>
                  </ErpPressable>
                </div>
              </div>

              <div className="flex items-center gap-4 mt-4">
                <label className="flex items-center gap-2 text-[var(--sds-text-primary)] text-sm">
                  <ErpInput
                    type="checkbox"
                    checked={newVariable.required}
                    onChange={(e) => setNewVariable({ ...newVariable, required: e.target.checked })}
                    className="rounded"
                  />
                  الزامی
                </label>
                <label className="flex items-center gap-2 text-[var(--sds-text-primary)] text-sm">
                  <ErpInput
                    type="checkbox"
                    checked={newVariable.autoGenerated}
                    onChange={(e) => setNewVariable({ ...newVariable, autoGenerated: e.target.checked })}
                    className="rounded"
                  />
                  تولید خودکار
                </label>
                <label className="flex items-center gap-2 text-[var(--sds-text-primary)] text-sm">
                  <ErpInput
                    type="checkbox"
                    checked={newVariable.calculated}
                    onChange={(e) => setNewVariable({ ...newVariable, calculated: e.target.checked })}
                    className="rounded"
                  />
                  محاسبه‌شده
                </label>
              </div>

              {errors.variable && <p className="text-[var(--sds-danger)] text-sm mt-2">{errors.variable}</p>}
            </SalesAuthoringSection>

            {/* Existing Variables */}
            <div>
              <h3 className="text-[var(--sds-text-primary)] font-medium mb-4">متغیرهای موجود</h3>
              {Object.keys(formData.variables).length === 0 ? (
                <p className="text-[var(--sds-text-muted)] text-center py-8">هنوز متغیری اضافه نشده است</p>
              ) : (
                <div className="space-y-2">
                  {Object.entries(formData.variables).map(([key, variable]) => (
                    <div key={key} className="flex items-center justify-between p-3 bg-[var(--sds-surface-raised)] rounded-lg">
                      <div className="flex items-center gap-4">
                        <div>
                          <span className="text-[var(--sds-text-primary)] font-medium">{variable.label}</span>
                          <span className="text-[var(--sds-text-muted)] text-sm mr-2">({key})</span>
                        </div>
                        <span className="text-[var(--sds-text-secondary)] text-sm">{variableTypes.find(t => t.value === variable.type)?.label}</span>
                        {variable.required && <span className="text-[var(--sds-danger)] text-xs">الزامی</span>}
                        {variable.autoGenerated && <span className="text-[var(--sds-info)] text-xs">خودکار</span>}
                        {variable.calculated && <span className="text-[var(--sds-success)] text-xs">محاسبه‌شده</span>}
                      </div>
                      <ErpPressable
                        type="button"
                        onClick={() => removeVariable(key)}
                        className="text-[var(--sds-danger)] hover:text-[var(--sds-danger)] p-1"
                      >
                        <FaTrash className="h-4 w-4" />
                      </ErpPressable>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </SalesAuthoringSection>
        )}

        {/* Structure Tab */}
        {activeTab === 'structure' && (
          <SalesAuthoringSection title="ساختار قالب" className="space-y-6">

            <div>
              <label className="block text-[var(--sds-text-primary)] font-medium mb-2">بخش‌های قالب</label>
              <div className="flex flex-wrap gap-2">
                {['header', 'table', 'footer'].map(section => (
                  <label key={section} className="flex items-center gap-2 text-[var(--sds-text-primary)] text-sm">
                    <ErpInput
                      type="checkbox"
                      checked={formData.structure.sections?.includes(section) || false}
                      onChange={(e) => {
                        const sections = formData.structure.sections || [];
                        if (e.target.checked) {
                          updateStructure('sections', [...sections, section]);
                        } else {
                          updateStructure('sections', sections.filter(s => s !== section));
                        }
                      }}
                      className="rounded"
                    />
                    {section === 'header' && 'سربرگ'}
                    {section === 'table' && 'جدول'}
                    {section === 'footer' && 'پاورقی'}
                  </label>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-[var(--sds-text-primary)] font-medium mb-2">حداکثر ردیف جدول</label>
              <ErpInput
                type="number"
                value={formData.structure.tableConfig?.maxRows || 9}
                onChange={(e) => updateStructure('tableConfig', {
                  ...formData.structure.tableConfig,
                  maxRows: parseInt(e.target.value)
                })}
                className="w-32"
                min="1"
                max="20"
              />
            </div>
          </SalesAuthoringSection>
        )}

        {/* Calculations Tab */}
        {activeTab === 'calculations' && (
          <SalesAuthoringSection title="فرمول‌های محاسباتی" className="space-y-6">

            <div>
              <label className="block text-[var(--sds-text-primary)] font-medium mb-2">فرمول‌های محاسباتی</label>
              <div className="space-y-4">
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">محاسبه متر مربع</label>
                  <ErpInput
                    type="text"
                    value={formData.calculations.formulas?.squareMeter || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      squareMeter: e.target.value
                    })}
                    className="w-full"
                    placeholder="length * width"
                  />
                </div>
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">محاسبه قیمت کل</label>
                  <ErpInput
                    type="text"
                    value={formData.calculations.formulas?.totalPrice || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      totalPrice: e.target.value
                    })}
                    className="w-full"
                    placeholder="squareMeter * unitPrice"
                  />
                </div>
                <div>
                  <label className="block text-[var(--sds-text-primary)] text-sm mb-1">محاسبه مجموع کل</label>
                  <ErpInput
                    type="text"
                    value={formData.calculations.formulas?.totalAmount || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      totalAmount: e.target.value
                    })}
                    className="w-full"
                    placeholder="SUM(totalPrice)"
                  />
                </div>
              </div>
            </div>

            <div>
              <label className="flex items-center gap-2 text-[var(--sds-text-primary)]">
                <ErpInput
                  type="checkbox"
                  checked={formData.calculations.persianNumberConversion || false}
                  onChange={(e) => updateCalculations('persianNumberConversion', e.target.checked)}
                  className="rounded"
                />
                تبدیل اعداد به فارسی
              </label>
            </div>
          </SalesAuthoringSection>
        )}

        {/* Submit Button */}
        <div className="flex items-center justify-end gap-4">
          <ErpButton label="انصراف" href="/dashboard/contract-templates" variant="ghost" tone="neutral" />
          <ErpPressable
            type="submit"
            disabled={loading}
            tone="primary"
            variant="solid"
            className="px-8 py-3 flex items-center gap-2 disabled:opacity-50"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-[var(--sds-border-default)]"></div>
                <span>در حال ایجاد...</span>
              </>
            ) : (
              <>
                <FaSave className="h-5 w-5" />
                <span>ایجاد قالب</span>
              </>
            )}
          </ErpPressable>
        </div>
      </form>
    </SalesAuthoringPage>
  );
}
