'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { 
  FaArrowRight, 
  FaSave, 
  FaEye, 
  FaFileContract,
  FaPlus,
  FaTrash,
  FaCode,
  FaTable,
  FaCalculator
} from 'react-icons/fa';
import { contractTemplatesAPI } from '@/lib/api';

interface TemplateVariable {
  key: string;
  type: 'text' | 'number' | 'date' | 'array';
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  calculated?: boolean;
  fields?: Record<string, TemplateVariable>;
}

interface TemplateStructure {
  sections: string[];
  tableConfig: {
    maxRows: number;
    columns: Array<{
      key: string;
      label: string;
      type: string;
      required?: boolean;
      autoIncrement?: boolean;
      calculated?: boolean;
    }>;
  };
}

interface TemplateCalculations {
  formulas: Record<string, string>;
  persianNumberConversion: boolean;
}

export default function CreateContractTemplatePage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [activeTab, setActiveTab] = useState<'basic' | 'content' | 'variables' | 'structure' | 'calculations'>('basic');

  const [formData, setFormData] = useState({
    name: '',
    namePersian: '',
    description: '',
    category: 'sales',
    content: '',
    variables: {} as Record<string, TemplateVariable>,
    structure: {} as TemplateStructure,
    calculations: {} as TemplateCalculations
  });

  const [newVariable, setNewVariable] = useState({
    key: '',
    type: 'text' as const,
    label: '',
    required: false,
    autoGenerated: false,
    calculated: false
  });

  const categories = [
    { value: 'sales', label: 'ÙØ±Ùˆش' },
    { value: 'service', label: 'خد�&ات' },
    { value: 'maintenance', label: 'نگهداری' },
    { value: 'general', label: 'Ø¹Ù…Ùˆمی' }
  ];

  const variableTypes = [
    { value: 'text', label: 'متن' },
    { value: 'number', label: 'عدد' },
    { value: 'date', label: 'تار�Rخ' },
    { value: 'array', label: 'آرایه' }
  ];

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    if (!formData.name.trim()) {
      newErrors.name = 'نام قالب الزامی است';
    }
    if (!formData.namePersian.trim()) {
      newErrors.namePersian = 'نام فارسی قالب الزامی است';
    }
    if (!formData.content.trim()) {
      newErrors.content = 'Ù…Ø­ØªÙˆای قالب الزامی است';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) {
      return;
    }

    setLoading(true);
    try {
      const response = await contractTemplatesAPI.create({
        name: formData.name,
        namePersian: formData.namePersian,
        description: formData.description || undefined,
        category: formData.category,
        content: formData.content,
        variables: Object.keys(formData.variables).length > 0 ? formData.variables : undefined,
        structure: Object.keys(formData.structure).length > 0 ? formData.structure : undefined,
        calculations: Object.keys(formData.calculations).length > 0 ? formData.calculations : undefined
      });

      if (response.data.success) {
        router.push('/dashboard/contract-templates');
      } else {
        setErrors({ general: response.data.error || 'خطا در ایجاد قالب' });
      }
    } catch (error: any) {
      console.error('Create template error:', error);
      setErrors({ general: error.response?.data?.error || 'خطا در ارتباط با سرور' });
    } finally {
      setLoading(false);
    }
  };

  const addVariable = () => {
    if (!newVariable.key || !newVariable.label) {
      setErrors({ variable: 'کلید و برچسب متغیر الزامی است' });
      return;
    }

    if (formData.variables[newVariable.key]) {
      setErrors({ variable: 'متغیر با این کلید قبلاً ÙˆØ¬Ùˆد دارد' });
      return;
    }

    setFormData({
      ...formData,
      variables: {
        ...formData.variables,
        [newVariable.key]: { ...newVariable }
      }
    });

    setNewVariable({
      key: '',
      type: 'text',
      label: '',
      required: false,
      autoGenerated: false,
      calculated: false
    });
    setErrors({});
  };

  const removeVariable = (key: string) => {
    const newVariables = { ...formData.variables };
    delete newVariables[key];
    setFormData({ ...formData, variables: newVariables });
  };

  const updateStructure = (field: keyof TemplateStructure, value: any) => {
    setFormData({
      ...formData,
      structure: {
        ...formData.structure,
        [field]: value
      }
    });
  };

  const updateCalculations = (field: keyof TemplateCalculations, value: any) => {
    setFormData({
      ...formData,
      calculations: {
        ...formData.calculations,
        [field]: value
      }
    });
  };

  const tabs = [
    { id: 'basic', label: 'اطلاعات پایه', icon: FaFileContract },
    { id: 'content', label: 'Ù…Ø­ØªÙˆای قالب', icon: FaCode },
    { id: 'variables', label: 'متغیرها', icon: FaTable },
    { id: 'structure', label: 'ساختار', icon: FaTable },
    { id: 'calculations', label: '�&حاسبات', icon: FaCalculator }
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">ایجاد قالب قرارداد جدید</h1>
          <p className="text-gray-300 mt-1">قالب جدید برای قراردادهای ÙØ±Ùˆش</p>
        </div>
        <Link 
          href="/dashboard/contract-templates"
          className="glass-liquid-btn px-6 py-3 flex items-center gap-2"
        >
          <FaArrowRight className="h-5 w-5" />
          <span>بازگشت</span>
        </Link>
      </div>

      {/* Error Display */}
      {errors.general && (
        <div className="glass-liquid-card p-4 bg-red-500/10 border border-red-500/20">
          <p className="text-red-400">{errors.general}</p>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Tab Navigation */}
        <div className="glass-liquid-card p-2">
          <div className="flex flex-wrap gap-2">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  type="button"
                  onClick={() => setActiveTab(tab.id as any)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all duration-200 ${
                    activeTab === tab.id
                      ? 'glass-liquid-btn-primary'
                      : 'glass-liquid-btn'
                  }`}
                >
                  <Icon className="h-4 w-4" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Basic Information Tab */}
        {activeTab === 'basic' && (
          <div className="glass-liquid-card p-6 space-y-6">
            <h2 className="text-xl font-semibold text-white mb-4">اطلاعات پایه</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-white font-medium mb-2">نام قالب (انگلیسی)</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="glass-liquid-input w-full"
                  placeholder="Sales Contract Template"
                />
                {errors.name && <p className="text-red-400 text-sm mt-1">{errors.name}</p>}
              </div>

              <div>
                <label className="block text-white font-medium mb-2">نام قالب (فارسی)</label>
                <input
                  type="text"
                  value={formData.namePersian}
                  onChange={(e) => setFormData({ ...formData, namePersian: e.target.value })}
                  className="glass-liquid-input w-full"
                  placeholder="قالب قرارداد ÙØ±Ùˆش"
                />
                {errors.namePersian && <p className="text-red-400 text-sm mt-1">{errors.namePersian}</p>}
              </div>

              <div>
                <label className="block text-white font-medium mb-2">دسته‌بندی</label>
                <select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="glass-liquid-input w-full"
                >
                  {categories.map(cat => (
                    <option key={cat.value} value={cat.value}>{cat.label}</option>
                  ))}
                </select>
              </div>

              <div className="md:col-span-2">
                <label className="block text-white font-medium mb-2">ØªÙˆضیحات</label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="glass-liquid-input w-full h-24"
                  placeholder="ØªÙˆضیحات Ú©Ùˆتاه درباره قالب..."
                />
              </div>
            </div>
          </div>
        )}

        {/* Content Tab */}
        {activeTab === 'content' && (
          <div className="glass-liquid-card p-6 space-y-6">
            <h2 className="text-xl font-semibold text-white mb-4">Ù…Ø­ØªÙˆای قالب</h2>
            
            <div>
              <label className="block text-white font-medium mb-2">Ù…Ø­ØªÙˆای HTML قالب</label>
              <textarea
                value={formData.content}
                onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                className="glass-liquid-input w-full h-96 font-mono text-sm"
                placeholder="Ù…Ø­ØªÙˆای HTML قالب با متغیرهای {{variableName}}..."
              />
              {errors.content && <p className="text-red-400 text-sm mt-1">{errors.content}</p>}
            </div>

            <div className="bg-gray-800/50 p-4 rounded-lg">
              <h3 className="text-white font-medium mb-2">راهنمای متغیرها:</h3>
              <ul className="text-gray-300 text-sm space-y-1">
                <li>• از {'{{variableName}}'} برای متغیرها استفاده کنید</li>
                <li>• از {'{{tableRows}}'} برای ردیف‌های Ø¬Ø¯Ùˆل استفاده کنید</li>
                <li>• از CSS inline برای استایل‌دهی استفاده کنید</li>
                <li>• جهت RTL و ÙÙˆنت فارسی را در نظر بگیرید</li>
              </ul>
            </div>
          </div>
        )}

        {/* Variables Tab */}
        {activeTab === 'variables' && (
          <div className="glass-liquid-card p-6 space-y-6">
            <h2 className="text-xl font-semibold text-white mb-4">متغیرهای قالب</h2>
            
            {/* Add New Variable */}
            <div className="glass-liquid-card p-4">
              <h3 className="text-white font-medium mb-4">Ø§ÙØ²Ùˆدن متغیر جدید</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div>
                  <label className="block text-white text-sm mb-1">کلید متغیر</label>
                  <input
                    type="text"
                    value={newVariable.key}
                    onChange={(e) => setNewVariable({ ...newVariable, key: e.target.value })}
                    className="glass-liquid-input w-full"
                    placeholder="buyerName"
                  />
                </div>
                <div>
                  <label className="block text-white text-sm mb-1">بر� سب</label>
                  <input
                    type="text"
                    value={newVariable.label}
                    onChange={(e) => setNewVariable({ ...newVariable, label: e.target.value })}
                    className="glass-liquid-input w-full"
                    placeholder="نام خریدار"
                  />
                </div>
                <div>
                  <label className="block text-white text-sm mb-1">Ù†Ùˆع</label>
                  <select
                    value={newVariable.type}
                    onChange={(e) => setNewVariable({ ...newVariable, type: e.target.value as any })}
                    className="glass-liquid-input w-full"
                  >
                    {variableTypes.map(type => (
                      <option key={type.value} value={type.value}>{type.label}</option>
                    ))}
                  </select>
                </div>
                <div className="flex items-end">
                  <button
                    type="button"
                    onClick={addVariable}
                    className="glass-liquid-btn-primary px-4 py-2 w-full flex items-center justify-center gap-2"
                  >
                    <FaPlus className="h-4 w-4" />
                    <span>Ø§ÙØ²Ùˆدن</span>
                  </button>
                </div>
              </div>
              
              <div className="flex items-center gap-4 mt-4">
                <label className="flex items-center gap-2 text-white text-sm">
                  <input
                    type="checkbox"
                    checked={newVariable.required}
                    onChange={(e) => setNewVariable({ ...newVariable, required: e.target.checked })}
                    className="rounded"
                  />
                  الزامی
                </label>
                <label className="flex items-center gap-2 text-white text-sm">
                  <input
                    type="checkbox"
                    checked={newVariable.autoGenerated}
                    onChange={(e) => setNewVariable({ ...newVariable, autoGenerated: e.target.checked })}
                    className="rounded"
                  />
                  ØªÙˆلید Ø®Ùˆدکار
                </label>
                <label className="flex items-center gap-2 text-white text-sm">
                  <input
                    type="checkbox"
                    checked={newVariable.calculated}
                    onChange={(e) => setNewVariable({ ...newVariable, calculated: e.target.checked })}
                    className="rounded"
                  />
                  محاسبه‌شده
                </label>
              </div>
              
              {errors.variable && <p className="text-red-400 text-sm mt-2">{errors.variable}</p>}
            </div>

            {/* Existing Variables */}
            <div>
              <h3 className="text-white font-medium mb-4">متغیرهای Ù…ÙˆØ¬Ùˆد</h3>
              {Object.keys(formData.variables).length === 0 ? (
                <p className="text-gray-400 text-center py-8">Ù‡Ù†Ùˆز متغیری اضافه نشده است</p>
              ) : (
                <div className="space-y-2">
                  {Object.entries(formData.variables).map(([key, variable]) => (
                    <div key={key} className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                      <div className="flex items-center gap-4">
                        <div>
                          <span className="text-white font-medium">{variable.label}</span>
                          <span className="text-gray-400 text-sm mr-2">({key})</span>
                        </div>
                        <span className="text-gray-500 text-sm">{variableTypes.find(t => t.value === variable.type)?.label}</span>
                        {variable.required && <span className="text-red-400 text-xs">الزامی</span>}
                        {variable.autoGenerated && <span className="text-blue-400 text-xs">Ø®Ùˆدکار</span>}
                        {variable.calculated && <span className="text-green-400 text-xs">محاسبه‌شده</span>}
                      </div>
                      <button
                        type="button"
                        onClick={() => removeVariable(key)}
                        className="text-red-400 hover:text-red-300 p-1"
                      >
                        <FaTrash className="h-4 w-4" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Structure Tab */}
        {activeTab === 'structure' && (
          <div className="glass-liquid-card p-6 space-y-6">
            <h2 className="text-xl font-semibold text-white mb-4">ساختار قالب</h2>
            
            <div>
              <label className="block text-white font-medium mb-2">بخش‌های قالب</label>
              <div className="flex flex-wrap gap-2">
                {['header', 'table', 'footer'].map(section => (
                  <label key={section} className="flex items-center gap-2 text-white text-sm">
                    <input
                      type="checkbox"
                      checked={formData.structure.sections?.includes(section) || false}
                      onChange={(e) => {
                        const sections = formData.structure.sections || [];
                        if (e.target.checked) {
                          updateStructure('sections', [...sections, section]);
                        } else {
                          updateStructure('sections', sections.filter(s => s !== section));
                        }
                      }}
                      className="rounded"
                    />
                    {section === 'header' && 'سربرگ'}
                    {section === 'table' && 'Ø¬Ø¯Ùˆل'}
                    {section === 'footer' && 'Ù¾Ø§Ùˆرقی'}
                  </label>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-white font-medium mb-2">حداکثر ردیف Ø¬Ø¯Ùˆل</label>
              <input
                type="number"
                value={formData.structure.tableConfig?.maxRows || 9}
                onChange={(e) => updateStructure('tableConfig', {
                  ...formData.structure.tableConfig,
                  maxRows: parseInt(e.target.value)
                })}
                className="glass-liquid-input w-32"
                min="1"
                max="20"
              />
            </div>
          </div>
        )}

        {/* Calculations Tab */}
        {activeTab === 'calculations' && (
          <div className="glass-liquid-card p-6 space-y-6">
            <h2 className="text-xl font-semibold text-white mb-4">ÙØ±Ù…Ùˆل‌های محاسباتی</h2>
            
            <div>
              <label className="block text-white font-medium mb-2">ÙØ±Ù…Ùˆل‌های محاسباتی</label>
              <div className="space-y-4">
                <div>
                  <label className="block text-white text-sm mb-1">محاسبه متر مربع</label>
                  <input
                    type="text"
                    value={formData.calculations.formulas?.squareMeter || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      squareMeter: e.target.value
                    })}
                    className="glass-liquid-input w-full"
                    placeholder="length * width"
                  />
                </div>
                <div>
                  <label className="block text-white text-sm mb-1">محاسبه قیمت کل</label>
                  <input
                    type="text"
                    value={formData.calculations.formulas?.totalPrice || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      totalPrice: e.target.value
                    })}
                    className="glass-liquid-input w-full"
                    placeholder="squareMeter * unitPrice"
                  />
                </div>
                <div>
                  <label className="block text-white text-sm mb-1">محاسبه Ù…Ø¬Ù…Ùˆع کل</label>
                  <input
                    type="text"
                    value={formData.calculations.formulas?.totalAmount || ''}
                    onChange={(e) => updateCalculations('formulas', {
                      ...formData.calculations.formulas,
                      totalAmount: e.target.value
                    })}
                    className="glass-liquid-input w-full"
                    placeholder="SUM(totalPrice)"
                  />
                </div>
              </div>
            </div>

            <div>
              <label className="flex items-center gap-2 text-white">
                <input
                  type="checkbox"
                  checked={formData.calculations.persianNumberConversion || false}
                  onChange={(e) => updateCalculations('persianNumberConversion', e.target.checked)}
                  className="rounded"
                />
                تبدیل اعداد به فارسی
              </label>
            </div>
          </div>
        )}

        {/* Submit Button */}
        <div className="flex items-center justify-end gap-4">
          <Link 
            href="/dashboard/contract-templates"
            className="glass-liquid-btn px-6 py-3"
          >
            ا� صراف
          </Link>
          <button
            type="submit"
            disabled={loading}
            className="glass-liquid-btn-primary px-8 py-3 flex items-center gap-2 disabled:opacity-50"
          >
            {loading ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                <span>در حال ایجاد...</span>
              </>
            ) : (
              <>
                <FaSave className="h-5 w-5" />
                <span>ایجاد قالب</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
