import assert from 'node:assert/strict';
import path from 'node:path';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { createAccountingLedgerAdministration } from '../accountingLedgerAdministration';
import { createCustomerPostingRulePrisma, projectCustomerAccountPrisma, customerStatementMovements, exportCustomerStatementPrisma } from '../accountingCustomerTreasuryPrisma';
import * as XLSX from 'xlsx';
import { listCustomerWorkspaceAccounts, readCustomerWorkspace, recordCustomerAccountOperation, recordCustomerWorkspaceTreasury } from '../accountingCustomerWorkspace';
import { listPostedTrialBalance } from '../accountingLedgerPrismaRepository';
import { createTemporaryConcurrencyDatabase } from './shipmentStatementConcurrency/database';
const sourceDatabaseUrl = process.env.ACCOUNTING_LEDGER_TEST_DATABASE_URL;

test('customer workspace: exact balances, immutable history, refund limits and CRM-only accounts', { skip: !sourceDatabaseUrl, timeout: 240_000 }, async () => {
  const temporary = await createTemporaryConcurrencyDatabase({ repositoryRoot: path.resolve(process.cwd(), '..'), sourceDatabaseUrl: sourceDatabaseUrl!, migrateEmptySchema: true });
  const db = temporary.client();
  try {
    const actor = { id: 'workspace-accountant', profile: 'ACCOUNTANT' as const };
    const administration = createAccountingLedgerAdministration(db);
    const entity = await administration.setup({ legalEntity: { code: 'workspace-test', namePersian: 'شرکت آزمون', activeFrom: new Date('2026-01-01') }, book: { code: 'primary', namePersian: 'دفتر اصلی' }, scheme: { groupLength: 1, kolLength: 2, moinLength: 3 }, actorId: actor.id });
    const book = entity.books[0]; const scheme = book.codeSchemes[0];
    const year = await administration.createFiscalYear({ bookId: book.id, code: '2026', titlePersian: 'سال آزمون', actorId: actor.id, startsAt: new Date('2026-01-01'), endsAt: new Date('2026-12-31T23:59:59.999Z'), periods: [{ code: '1', titlePersian: 'دوره آزمون', sequence: 1, isAdjustment: false, startsAt: new Date('2026-01-01'), endsAt: new Date('2026-12-31T23:59:59.999Z') }] });
    const makeAccount = async (code: string, title: string, party = false, financial = false, statementRole: 'ASSET' | 'LIABILITY' | 'REVENUE' | 'EXPENSE' = 'ASSET', normalSide: 'DEBIT' | 'CREDIT' = 'DEBIT') => {
      const common = { bookId: book.id, codeSchemeId: scheme.id, normalSide, statementRole, currencyBehavior: 'BASE_ONLY' as const, effectiveFrom: year.startsAt, actorId: actor.id };
      const group = await administration.createAccount({ ...common, code, titlePersian: `${title} گروه`, level: 'GROUP' });
      const kol = await administration.createAccount({ ...common, code: `${code}01`, titlePersian: `${title} کل`, parentId: group.id, level: 'KOL' });
      return administration.createAccount({ ...common, code: `${code}01001`, titlePersian: title, parentId: kol.id, level: 'MOIN', partyRequirement: party ? 'REQUIRED' : 'FORBIDDEN', financialAccountRequirement: financial ? 'REQUIRED' : 'FORBIDDEN' });
    };
    const [receivable, advance, bank, counter, tax, inventory, cost] = await Promise.all([makeAccount('1', 'دریافتنی', true), makeAccount('2', 'پیش‌دریافت', true, false, 'LIABILITY', 'CREDIT'), makeAccount('3', 'بانک', false, true), makeAccount('4', 'حساب مقابل', false, false, 'REVENUE', 'CREDIT'), makeAccount('5', 'مالیات', false, false, 'LIABILITY', 'CREDIT'), makeAccount('6', 'موجودی'), makeAccount('7', 'بهای تمام‌شده', false, false, 'EXPENSE')]);
    const rule = await createCustomerPostingRulePrisma(db, { legalEntityId: entity.id, code: 'default', version: 1, receivableAccountId: receivable.id, customerAdvanceAccountId: advance.id, bankClearingAccountId: bank.id, revenueAccountId: counter.id, outputTaxAccountId: tax.id, inventoryAccountId: inventory.id, costAccountId: cost.id, effectiveFrom: year.startsAt, actor: { ...actor, profile: 'ACCOUNTING_MANAGER' } });
    const financial = await administration.createFinancialAccount({ legalEntityId: entity.id, kind: 'BANK', titlePersian: 'بانک آزمون', currency: 'IRR', activeFrom: year.startsAt, actorId: actor.id });
    const customer = await db.crmCustomer.create({ data: { firstName: 'مشتری', lastName: 'خاص', trustCategory: 'SPECIAL' } });
    await db.crmCustomer.create({ data: { firstName: 'مشتری', lastName: 'بدون گردش' } });
    const id = `customer:${customer.id}`;
    const initial = await readCustomerWorkspace(db, { id, asOf: new Date(), userId: actor.id });
    assert.equal(initial.netBalanceRials, 0n); assert.equal(initial.profile, null);
    assert.equal(await db.accountingCustomerProfile.count(), 0, 'reading must not provision a profile');
    const list = await listCustomerWorkspaceAccounts(db, { asOf: new Date(), pageSize: 1 });
    assert.equal(list.total, 2); assert.equal(list.items.length, 1);
    const common = { periodId: year.periods[0].id, postingRuleId: rule.id, counterAccountId: counter.id, occurredAt: new Date('2026-10-01'), reason: 'ثبت مالی با مستندات آزمون', reference: 'نامه شماره یک', confirmed: true, actor };
    const opening = { ...common, kind: 'OPENING' as const, amountRials: 1000n, idempotencyKey: randomUUID() };
    const result = await recordCustomerAccountOperation(db, id, opening);
    assert.deepEqual(await recordCustomerAccountOperation(db, id, opening), result);
    const profileId = result.profileId;
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...opening, amountRials: 2000n }), /اطلاعات دیگری/);
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...opening, idempotencyKey: randomUUID() }), /قبلاً ثبت/);
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...common, kind: 'DEBIT', amountRials: 10n, idempotencyKey: randomUUID(), actor: { ...actor, profile: 'VIEWER' } }), /مجوز/);
    const receipt = await recordCustomerWorkspaceTreasury(db, id, { ...common, occurredAt: new Date('2026-10-02'), kind: 'RECEIPT', amountRials: 600n, bankLedgerId: bank.id, financialAccountId: financial.id, idempotencyKey: randomUUID(), allocations: [] });
    const receiptId = (receipt as { id: string }).id;
    let projected = await projectCustomerAccountPrisma(db, { profileId, asOf: new Date() });
    assert.equal(projected.receivableRials - projected.unallocatedCreditRials, 400n);
    assert.equal(projected.activityItems[0].occurredAt.toISOString(), '2026-10-01T00:00:00.000Z');
    assert.deepEqual(customerStatementMovements(projected).map(row => row.balance), ['1000', '400']);
    const exported = await exportCustomerStatementPrisma(db, { profileId, asOf: new Date(), format: 'xlsx', actorId: actor.id });
    const workbook = XLSX.read(exported.bytes);
    const rows = XLSX.utils.sheet_to_json<Record<string, string>>(workbook.Sheets[workbook.SheetNames[0]]);
    assert.deepEqual(rows.map(row => row['مانده']), ['1000', '400']);
    if (process.env.CUSTOMER_WORKSPACE_QA_OUTPUT) {
      const output = process.env.CUSTOMER_WORKSPACE_QA_OUTPUT;
      await mkdir(output, { recursive: true });
      await writeFile(path.join(output, 'customer-statement.xlsx'), exported.bytes);
      const pdf = await exportCustomerStatementPrisma(db, { profileId, asOf: new Date(), format: 'pdf', actorId: actor.id });
      assert.equal(pdf.bytes.subarray(0, 4).toString(), '%PDF');
      await writeFile(path.join(output, 'customer-statement.pdf'), pdf.bytes);
    }
    const item = projected.openItems[0];
    const allocate = { ...common, kind: 'ALLOCATION' as const, amountRials: 0n, receiptId, idempotencyKey: randomUUID(), allocations: [{ openItemId: item.id, amountRials: 300n }] };
    const allocation = await recordCustomerWorkspaceTreasury(db, id, allocate);
    await assert.rejects(recordCustomerWorkspaceTreasury(db, id, { ...allocate, idempotencyKey: randomUUID(), allocations: [allocate.allocations[0], allocate.allocations[0]] }), /یک بار/);
    const refund = { ...common, kind: 'REFUND' as const, amountRials: 100n, receiptId, financialAccountId: financial.id, bankLedgerId: bank.id, idempotencyKey: randomUUID() };
    await recordCustomerAccountOperation(db, id, refund);
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...refund, amountRials: 201n, idempotencyKey: randomUUID() }), /قابل استرداد/);
    await assert.rejects(recordCustomerWorkspaceTreasury(db, id, { ...allocate, idempotencyKey: randomUUID(), allocations: [{ openItemId: item.id, amountRials: 201n }] }), /مانده دریافت/);
    projected = await projectCustomerAccountPrisma(db, { profileId, asOf: new Date() });
    assert.equal(projected.receivableRials, 700n); assert.equal(projected.unallocatedCreditRials, 200n);
    const adjust = { ...common, kind: 'SET_BALANCE' as const, amountRials: 450n, expectedBalanceRials: 500n, idempotencyKey: randomUUID() };
    await recordCustomerAccountOperation(db, id, adjust);
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...adjust, idempotencyKey: randomUUID() }), /مانده مشتری تغییر/);
    await recordCustomerAccountOperation(db, id, { ...common, kind: 'CREDIT', amountRials: 150n, idempotencyKey: randomUUID() });
    projected = await projectCustomerAccountPrisma(db, { profileId, asOf: new Date() });
    const credit = projected.openItems.find(row => row.kind === 'CREDIT' && row.originalRials === 150n)!;
    await recordCustomerAccountOperation(db, id, { ...refund, receiptId: undefined, creditItemId: credit.id, amountRials: 100n, idempotencyKey: randomUUID() });
    projected = await projectCustomerAccountPrisma(db, { profileId, asOf: new Date() });
    assert.equal(projected.openItems.find(row => row.id === credit.id)?.remainingRials, 50n);
    assert.equal(projected.receivableRials - projected.unallocatedCreditRials, 400n);
    await recordCustomerWorkspaceTreasury(db, id, { ...common, kind: 'REVERSE_ALLOCATION', amountRials: 0n, allocationId: (allocation as { id: string }).id, allocations: [], idempotencyKey: randomUUID() });
    projected = await projectCustomerAccountPrisma(db, { profileId, asOf: new Date() });
    assert.equal(projected.receivableRials - projected.unallocatedCreditRials, 400n);
    assert.equal(projected.activityItems.find(row => row.id === item.id)?.originalRials, 1000n);
    assert.equal(customerStatementMovements(projected).at(-1)?.balance, '400');
    await db.accountingCheckInstrument.create({ data: { legalEntityId: entity.id, profileId, direction: 'INBOUND', serialNumber: 'check-workspace', bankName: 'بانک آزمون', amountRials: '500', dueAt: new Date('2026-10-04'), status: 'BOUNCED', evidenceHash: 'test-evidence', createdBy: actor.id } });
    const workspace = await readCustomerWorkspace(db, { id, asOf: new Date(), userId: actor.id });
    assert.equal(workspace.treasuryChecks.length, 1);
    assert.equal(workspace.netBalanceRials, 400n);
    const trial = await listPostedTrialBalance(db, { bookId: book.id, fiscalYearId: year.id });
    assert.ok(trial.length > 0);
    assert.equal(trial.reduce((sum, row) => sum + BigInt(row.debitRials.toString()), 0n), trial.reduce((sum, row) => sum + BigInt(row.creditRials.toString()), 0n));
    await db.accountingPostingPeriod.update({ where: { id: year.periods[0].id }, data: { status: 'HARD_CLOSED' } });
    const count = await db.accountingLedgerVoucher.count();
    await assert.rejects(recordCustomerAccountOperation(db, id, { ...common, kind: 'DEBIT', amountRials: 10n, idempotencyKey: randomUUID() }), /باز نیست/);
    assert.equal(await db.accountingLedgerVoucher.count(), count);
  } finally { await db.$disconnect(); await temporary.cleanup(); }
});
