const actions: Record<string, string> = {
  view: 'مشاهده',
  create: 'ایجاد',
  edit: 'ویرایش',
  delete: 'حذف',
  approve: 'تأیید',
  reject: 'رد',
  sign: 'امضا',
  print: 'چاپ',
  import: 'ورود اطلاعات',
  export: 'خروجی',
  update: 'به‌روزرسانی',
  toggle: 'تغییر وضعیت',
  start: 'شروع',
  end: 'پایان',
  assign: 'تخصیص',
  verify: 'تأیید',
  validate: 'اعتبارسنجی',
  send: 'ارسال',
  stats: 'آمار',
  manage: 'مدیریت',
  lock: 'قفل',
  blacklist: 'فهرست سیاه',
  reassign: 'تخصیص مجدد',
  request: 'درخواست',
  finalize: 'نهایی‌سازی',
  cancel: 'لغو',
};

const tokens: Record<string, string> = {
  core: 'هسته',
  dashboard: 'داشبورد',
  profile: 'پروفایل',
  departments: 'بخش‌ها',
  posts: 'سمت‌ها',
  orders: 'سفارش‌ها',
  customers: 'مشتریان',
  customer: 'مشتری',
  project: 'پروژه',
  projects: 'پروژه‌ها',
  potential: 'بالقوه',
  addresses: 'نشانی‌ها',
  phone: 'تلفن',
  numbers: 'شماره‌ها',
  contacts: 'مخاطبان',
  leads: 'سرنخ‌ها',
  communications: 'ارتباطات',
  contracts: 'قراردادها',
  contract: 'قرارداد',
  items: 'اقلام',
  deliveries: 'تحویل‌ها',
  payments: 'پرداخت‌ها',
  verification: 'اعتبارسنجی',
  number: 'شماره',
  templates: 'قالب‌ها',
  template: 'قالب',
  generate: 'تولید',
  products: 'محصولات',
  attributes: 'ویژگی‌ها',
  legacy: 'قدیمی',
  sales: 'فروش',
  crm: 'ارتباط با مشتری',
  inventory: 'انبار',
  hr: 'منابع انسانی',
  security: 'امنیت',
  support: 'پشتیبانی',
  incident: 'رخداد امنیتی',
  handle: 'رسیدگی',
  accounting: 'حسابداری',
  actions: 'عملیات',
  admin: 'مدیریت',
  after: 'پس از',
  approve: 'تأیید',
  assign: 'تخصیص',
  approval: 'تأیید',
  audit: 'ممیزی',
  blacklist: 'فهرست سیاه',
  cancel: 'لغو',
  candidates: 'پیش‌نویس اسناد',
  create: 'ایجاد',
  delete: 'حذف',
  edit: 'ویرایش',
  export: 'خروجی',
  invoice: 'صورتحساب',
  import: 'ورود اطلاعات',
  manage: 'مدیریت',
  receivables: 'دریافتنی‌ها',
  records: 'رکوردها',
  reject: 'رد',
  request: 'درخواست',
  tax: 'مالیات',
  update: 'به‌روزرسانی',
  void: 'ابطال',
  bi: 'هوش تجاری',
  logistics: 'لجستیک',
  loading: 'بارگیری',
  loadings: 'بارگیری‌ها',
  drivers: 'رانندگان',
  driver: 'راننده',
  corrections: 'اصلاحات',
  correction: 'اصلاح',
  cut: 'برش',
  cutting: 'برش',
  types: 'انواع',
  stone: 'سنگ',
  materials: 'مواد',
  widths: 'عرض‌ها',
  thicknesses: 'ضخامت‌ها',
  mines: 'معادن',
  finish: 'پرداخت',
  finishings: 'پرداخت‌ها',
  colors: 'رنگ‌ها',
  services: 'خدمات',
  service: 'خدمت',
  sub: 'زیرمجموعه',
  stair: 'پله',
  standard: 'استاندارد',
  lengths: 'طول‌ها',
  layer: 'لایه',
  layers: 'لایه‌ها',
  shifts: 'شیفت‌ها',
  attendance: 'حضور و غیاب',
  checkin: 'ورود',
  checkout: 'خروج',
  exception: 'استثنا',
  exceptions: 'استثناها',
  daily: 'روزانه',
  personnel: 'پرسنل',
  missions: 'مأموریت‌ها',
  signature: 'امضا',
  time: 'زمان',
  follow: 'پیگیری',
  ups: '',
  next: 'اقدام بعدی',
  owner: 'مالک',
  status: 'وضعیت',
  stats: 'آمار',
  reassign: 'تخصیص مجدد',
  send: 'ارسال',
  sign: 'امضا',
  print: 'چاپ',
  toggle: 'تغییر وضعیت',
  start: 'شروع',
  end: 'پایان',
  verify: 'تأیید',
  validate: 'اعتبارسنجی',
  view: 'مشاهده',
  type: 'نوع',
};

export const workspaceLabelFa = (workspace?: string | null) => {
  if (!workspace) return 'عمومی';
  return {
    sales: 'فروش',
    crm: 'مدیریت ارتباط با مشتری',
    hr: 'منابع انسانی',
    accounting: 'حسابداری',
    inventory: 'انبار',
    security: 'نگهبانی و امنیت',
    bi: 'هوش تجاری',
    logistics: 'لجستیک',
  }[workspace] || workspace;
};

export const featureLabelFa = (featureKey: string, suppliedLabel?: string) => {
  if (suppliedLabel && /[\u0600-\u06FF]/.test(suppliedLabel)) return suppliedLabel;
  const parts = featureKey.toLowerCase().split('_').filter(Boolean);
  const last = parts.at(-1) || '';
  const action = actions[last];
  const subjectParts = action ? parts.slice(0, -1) : parts;
  const subject = subjectParts.map((part) => tokens[part] || part).filter(Boolean).join(' ');
  return [action, subject].filter(Boolean).join(' ') || suppliedLabel || featureKey;
};
