'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { FaChevronDown, FaChevronUp, FaHistory, FaRedo } from 'react-icons/fa';
import { ErpBadge, ErpButton, ErpCard, ErpEmptyState, ErpLoading, ErpPage, ErpSection } from '@/components/erp';
import { securityAPI } from '@/lib/api';
import PersianCalendar from '@/lib/persian-calendar';
import PersianCalendarComponent from '@/components/PersianCalendar';

const dateTime = (value?: string | null) => value ? new Date(value).toLocaleString('fa-IR') : '—';
export default function SecurityPersonnelHistoryPage() {
  const { personnelId } = useParams<{ personnelId: string }>();
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState<string | null>(null); const [range, setRange] = useState<{ startDate: string; endDate: string } | null>(null);
  const load = async () => { try { setLoading(true); const result = await securityAPI.getSecurityPersonnelShiftHistory(personnelId, range ? { startDate: PersianCalendar.toGregorian(range.startDate).toISOString(), endDate: PersianCalendar.toGregorian(range.endDate).toISOString() } : undefined); setData(result.data.data); } catch (err: any) { setError(err.response?.data?.error || 'دریافت تاریخچه ناموفق بود.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [personnelId, range]);
  if (loading) return <ErpLoading />;
  if (error) return <ErpPage eyebrow="حراست" title="تاریخچه شیفت‌ها"><ErpEmptyState title="تاریخچه در دسترس نیست" description={error} icon={FaHistory} action={{ label: 'تلاش مجدد', onClick: load, icon: FaRedo }} /></ErpPage>;
  return <ErpPage eyebrow="حراست · گزارش‌های حراست" title={`تاریخچه شیفت‌های ${data.personnel.name}`} description={`فقط شیفت‌های پایان‌یافته · آخرین پایان در ابتدا · شیفت پایه: ${data.personnel.shift}`} backHref="/dashboard/security/reports">
    <ErpSection title="بازه اختیاری"><div className="grid grid-cols-1 gap-3 md:grid-cols-[1fr_1fr_auto]"><PersianCalendarComponent value={range?.startDate || ''} onChange={(startDate) => setRange((old) => ({ startDate, endDate: old?.endDate || startDate }))} placeholder="از تاریخ" /><PersianCalendarComponent value={range?.endDate || ''} onChange={(endDate) => setRange((old) => ({ startDate: old?.startDate || endDate, endDate }))} placeholder="تا تاریخ" /><ErpButton label="نمایش کل سابقه" variant="outline" onClick={() => setRange(null)} /></div></ErpSection>
    <ErpSection title="شیفت‌های پایان‌یافته" description="برای دیدن کامل جزئیات و گزارش‌های لحظه‌ای هر شیفت را باز کنید."><div className="space-y-3">{data.shifts.map((slot: any) => { const expanded = open === slot.id; const attendance = slot.attendance?.[0]; return <ErpCard key={slot.id} className="p-4"><button type="button" className="flex w-full items-start justify-between gap-3 text-right" onClick={() => setOpen(expanded ? null : slot.id)}><div><p className="font-bold">پایان: {dateTime(slot.session?.endedAt)}</p><p className="mt-1 text-sm text-slate-500">بازه برنامه: {dateTime(slot.startsAt)} تا {dateTime(slot.endsAt)} · وضعیت: {slot.session?.status === 'FORCE_CLOSED' ? 'بسته‌شده توسط مدیر' : 'تکمیل‌شده'}</p></div><span>{expanded ? <FaChevronUp /> : <FaChevronDown />}</span></button>{expanded && <div className="mt-4 space-y-4 border-t pt-4"><div className="grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><p>حضور: {dateTime(attendance?.arrivedAt)}</p><p>تأخیر: {attendance?.delayMinutes || 0} دقیقه</p><p>شروع: {dateTime(slot.session?.startedAt)}</p><p>پایان: {dateTime(slot.session?.endedAt)}</p><p>اضافه‌کار: {slot.session?.overtimeMinutes || 0} دقیقه</p></div>{slot.session?.closureSummary && <p className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800">خلاصه پایان: {slot.session.closureSummary}</p>}<div><h3 className="font-semibold">گزارش‌های لحظه‌ای</h3><div className="mt-2 space-y-2">{slot.session?.logEntries?.map((entry: any) => <div key={entry.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-2"><span>ردیف {entry.rowNumber} · {entry.reportType.name}</span><ErpBadge tone={entry.status === 'VOIDED' ? 'danger' : 'info'}>{entry.status === 'VOIDED' ? 'باطل شده' : 'فعال'}</ErpBadge></div>{entry.description && <p className="mt-2">{entry.description}</p>}{entry.participants?.length > 0 && <p className="mt-2 text-xs text-slate-500">افراد مرتبط: {entry.participants.map((p: any) => `${p.user.firstName} ${p.user.lastName}`).join('، ')}</p>}{entry.status === 'VOIDED' && <p className="mt-2 text-red-600">دلیل ابطال: {entry.voidReason} · {dateTime(entry.voidedAt)}</p>}</div>) || <p className="text-sm text-slate-500">گزارشی ثبت نشده است.</p>}</div></div><div><h3 className="font-semibold">گشت‌زنی‌ها</h3>{slot.session?.patrolSessions?.map((patrol: any) => <p key={patrol.id} className="mt-2 text-sm">{dateTime(patrol.startedAt)} تا {dateTime(patrol.endedAt)} · {patrol.description || 'بدون توضیح'}</p>) || <p className="mt-2 text-sm text-slate-500">گشتی ثبت نشده است.</p>}</div></div>}</ErpCard>; })}{!data.shifts.length && <ErpEmptyState icon={FaHistory} title="شیفت پایان‌یافته‌ای در این بازه وجود ندارد" />}</div></ErpSection>
  </ErpPage>;
}
